server:
  port: 16074
  context-path: /

spring:
  application:
    name: boot-es
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.204:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true