﻿server:
  port: 16087
  context-path: /
spring:
  application:
    name: boot-sharding-mybatis
#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yq.sharding.mybatis.entity
sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/simple_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:
            #主键
            key-generator-column-name: id
            #数据节点,均匀分布
            actual-data-nodes: ds0.t_user${0..1}
            #分表策略
            table-strategy:
              #行表达式
              inline:
                sharding-column: sex
                #按模运算分配
                algorithm-expression: ds0.t_user${sex % 2}
