server:
  port: 16001
  context-path: /

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      defaultZone: http://192.168.0.100:16000/eureka/,http://192.168.0.101:16000/eureka/

spring:
  application:
    name: BOOT-REDISSON
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/boot_dev?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
     max-file-size: 100MB

#  redisson 配置
  redisson:
    type: SENTINEL
    masterName: mymaster
    passWord: smstest
    sentinelAddresses:
      - "redis://192.168.0.100:8877"
      - "redis://192.168.0.101:8877"
      - "redis://192.168.0.102:8877"

